//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TREntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTax_Process
    {
        public int Auto_ID { get; set; }
        public string MonthYear { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Account { get; set; }
        public string JurCode { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> TaxBaseAmtBSET { get; set; }
        public Nullable<decimal> TaxAmtBSET { get; set; }
        public Nullable<decimal> TaxBaseAdjustment { get; set; }
        public Nullable<decimal> TaxBaseTxCodeZ4 { get; set; }
        public Nullable<decimal> TaxAmtAdjustment { get; set; }
        public Nullable<decimal> TaxAmtCalculated { get; set; }
        public Nullable<decimal> TaxPaid { get; set; }
        public string PST { get; set; }
        public string Ratio { get; set; }
        public string CompositeRate { get; set; }
        public string Note { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<bool> ValidationCompleted { get; set; }
        public Nullable<decimal> CalculatedAmount { get; set; }
        public Nullable<bool> C502012_Completed { get; set; }
        public Nullable<decimal> TaxNotApplied { get; set; }
        public Nullable<bool> HasBeenCalculated { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
